server:
  port: 8081

spring:
  application:
    name: paymentConsumer
  profiles:
    include: datasource, message
    group:
      dev: "datasource-dev, message-dev"
    active: dev

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  kafka:
    isConsumer: true
    consumer:
      groupId: 1
      subscribes:
        - "command-request-order"
        - "event-reject-order"
        - "event-confirm-order"

  payment:
    secretKey: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"
    confirmPaymentUrl: "https://api.tosspayments.com/v1/payments/confirm"