spring:
  config:
    activate:
      on-profile: message-dev

  kafka:
    bootstrapServer: 127.0.0.1:9093
    topics:
      requestOrder: "command-request-order"
      rejectOrder: "event-reject-order"
      confirmOrder: "event-confirm-order"
